version: '3'

services:
  project1:
    build:
      context: Receiver
      args:
        URL: "http://project2"
    ports:
      - 5000:80
    volumes:
      - './Receiver/src:/app'
    networks:
      - common
    depends_on:
      - project2
  project2:
    build: Sender
    volumes:
      - './Sender/src:/app'
    networks:
      - common
networks:
  common: